# Site settings
author: Victoria 
title: Making it to Software Engineer 
header-img: img/home-bg.png
email: victoriacurl9@gmail.com
copyright_name: Victoria 
description: > # this means to ignore newlines until "baseurl:"
  A journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  victoriacurl

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
